export const DBqueries = {
    GetLookupValues: "Select * From tbl_Lookup Where Is_Active = 'Y'",
    CheckIfUserExists: "Select Identification, User_Type, Is_Active, Frst_Name, Last_Name, Email, Refresh_Token, User_Id from tbl_User Where Identification = ?",
    CheckIfUserExistsByUserId: "Select * from tbl_User Where User_Id = ? And Is_Active = 'Y'",
    InsertUser: "Insert Into tbl_User(Firebase_Id, Identification, User_Id, User_Type, Frst_Name, Last_Name, Email, Refresh_Token, Is_Active) Values(?,?,?,?,?,?,?,?,?)",
    InsertPracDetails: "Insert Into tbl_Member(Member_Id) Values(?)",
    InsertSeekerDetails: "Insert Into tbl_Seeker(Seeker_Id) Values(?)",
    UpdatePracDetails: "Update tbl_Member INNER JOIN tbl_User ON tbl_User.User_Id = tbl_Member.Member_Id  AND tbl_User.Firebase_Id = ?  AND tbl_User.Is_Active = 'P' SET tbl_Member.Major = ?, tbl_Member.Specification = ?, tbl_Member.Experience = ?, tbl_Member.Updated_On = CURRENT_TIMESTAMP",
    UpdateUserStatus: "Update tbl_User Set Is_Active = ?, Updated_On = CURRENT_TIMESTAMP Where Firebase_Id = ? And Is_Active = ?",
    CheckRefreshToken: "Select Firebase_Id, Refresh_Token From tbl_User Where Refresh_Token = ? And Is_Active = 'Y'",
    UpdateRefreshToken: "Update tbl_User SET Refresh_Token = ?, Updated_On = CURRENT_TIMESTAMP Where Firebase_Id = ? And Is_Active = 'Y'",
    GetMaxUserId: "SELECT (SUBSTRING(User_Id, 5)+1) AS MaxId FROM tbl_User ORDER BY MaxId DESC LIMIT 1",
    CheckIfCresClient: "Select * From tbl_User Where Email = ? And Is_Active = 'Y'",
    CreateMeetingDetails: "Insert Into tbl_Meeting(Meeting_Id, Event_Id, Start_TS, End_TS, Member_Id, Description, Summary, Platform, Platform_Meeting_Id, Status) Values(?,?,?,?,?,?,?,?,?,?)",
    UpdateUserDetails: "Update tbl_User Set Frst_Name = ?, Last_Name = ?, Email = ?, Refresh_Token = ?, Updated_On = CURRENT_TIMESTAMP Where Identification = ? And Is_Active = ?",

    CreateTokenDetails: "Insert Into tbl_Token(Member_Id, Email, Access_Token, Refresh_Token) Values(?, ?, ?, ?)",
    SoftDeleteToken: "Update tbl_Token Set Is_Active = ?, Updated_On = CURRENT_TIMESTAMP Where Member_Id = ?",
    GetTokenDetails: "SELECT Access_Token, Refresh_Token FROM tbl_Token Where Member_Id = ? AND Is_Active = 'Y'",
    GetClientId: "Select Client_Id From tbl_Client Where Client_Iden = ? And Is_Active = 'Y'",

    // GetMemberInfo: "SELECT Identification, Frst_Name, Last_Name, Major_Desc, Spec_Desc, Email FROM vw_Member_Info Where User_Id = ?",
    // GetUpcomingMeetings: "SELECT 'Meeting' as Event_Type, Meeting_Id, Client_Iden, Client_Id, Member_Id, Start_TS, End_TS, Description, Summary, Platform_Meeting_Id FROM vw_Meeting_Det Where CAST(Start_TS AS DATE) >= CURDATE() And User_Id = ?",
    GetPatientInfo: "SELECT DISTINCT tbl_Client.Name, tbl_Client.Client_Iden, tbl_Client.Client_Id FROM tbl_Client INNER JOIN tbl_User ON tbl_Client.Is_Active = 'Y' AND tbl_User.Is_Active = 'Y' AND tbl_Client.Member_Id = tbl_User.User_Id AND tbl_User.User_Id = ?",
    SaveNotes: "Insert Into tbl_Note(Member_Id, Note_Id, Client_Id, Meeting_Id, Resource_Type, Resource) Values(?,?,?,?,?,?)",
    UpdateNotes: "Update tbl_Note Set Resource = ?, Updated_On = CURRENT_TIMESTAMP Where Note_Id = ?",
    CheckIfMeetingExists: "Select * From tbl_Meeting Where Meeting_Id = ? and Is_Active = ?",
    CheckIfClientExists: "Select * From tbl_Client Where Client_Id = ? and Is_Active = ?",
    CheckIfNotesExists: "Select * From tbl_Note Where Note_Id = ? And Resource_Type = ?",
    CheckIfNotesForMeetingExists: "Select * From tbl_Note Where Client_Id = ? and Meeting_Id = ? and Resource_Type = ?",
    SaveHolidayList: "Insert Into tbl_Holiday_List(Meeting_Id, Event_Id, Description, Status, Summary, Start_TS, End_TS) Values(?,?,?,?,?,?,?)",
    ValidateLookup: "Select * From tbl_Lookup Where Lookup_Cat = ? And Lookup_Val = ? and Is_Active = 'Y'",
    SaveFile: "Insert Into tbl_File(File_Id, Client_Id, Member_Id, Meeting_Id, File_Path) Values(?,?,?,?,?)",
    GetReminderTimeByEventId: "SELECT tbl_Member.Reminder_Time, tbl_Meeting.Start_TS FROM tbl_User INNER JOIN tbl_Member ON tbl_User.User_Id = tbl_Member.Member_Id AND tbl_User.Is_Active = 'Y' INNER JOIN tbl_Meeting ON tbl_Meeting.Member_Id = tbl_User.User_Id AND tbl_Meeting.Event_Id = ? AND tbl_Meeting.Is_Active = 'Y'",
    // GetReminderStatusByEventId: "SELECT * From vw_Upcoming_Appoinment Where Event_Id = ?",
    // GetUpcomingAppoinment: "Select * From vw_Upcoming_Appoinment",
    CreateJob: "Insert Into tbl_Job(Job_Name, Job_Id, Start_TS, Run_Status, Scheduled_TS) Values(?,?,?,?,?)",
    UpdateJob: "Update tbl_Job SET End_TS = CURRENT_TIMESTAMP, Run_Status = ?, Updated_On = CURRENT_TIMESTAMP Where Job_Id = ?",
    CreateLog: "Insert Into tbl_Log(Process_Name, Process_Type, User_Id, Job_Id, Event_Id, Meeting_Id, Error_Message) Values(?,?,?,?,?,?,?)",
    CreateApiLogs: "Insert Into tbl_Api_Log(Process_Name, Process_Type_Id, Process_Type_Value, Response) Values(?,?,?,?)",
    GetHolidayList: "Select * From tbl_Holiday_List Where Start_TS Between IF(MONTH(CURRENT_DATE()) <=6, str_to_date(CONCAT(year(now()) - 1, '07', '01'), '%Y%m%d'), str_to_date(CONCAT(year(now()), '01', '01'), '%Y%m%d')) And IF(MONTH(CURRENT_DATE()) <=6, str_to_date(CONCAT(year(now()) + 1, '06', '30'), '%Y%m%d'), str_to_date(CONCAT(year(now()) + 1, '12', '31'), '%Y%m%d'));",
    GetUserIdByExternalId: "Select User_Id From tbl_User Where Firebase_Id = ? And Is_Active = ?",
    UpdateUserEmailId: "Update tbl_User Set Email = ?, Updated_On = CURRENT_TIMESTAMP Where User_Id = ? And Is_Active = ?",

    GetFiles: "Select File_Id, File_Path, Created_On From tbl_File Where Client_Id = ? And Is_Active = ?",
    GetNote: "Select Resource, Resource_Type, Created_On From tbl_Note Where Note_Id = ?",
    ValidateMeetingIdWithUserId: "Select * From tbl_Meeting Where Meeting_Id = ? And Member_Id = ? And Is_Active = ?",
    CheckIfEmailAlreadyExists: "Select * from tbl_User Where Email = ?",
    DeleteFile: "Update tbl_File SET Is_Active = ?, Updated_On = CURRENT_TIMESTAMP Where File_Id = ?",
    FindClientDetails: "Select * From tbl_Client Where Client_Iden = ? And Name IS NOT NULL LIMIT 1",
    FindMeetingDetails: "Select * From tbl_Meeting Where Event_Id = ?",
    GetAllRefreshToken: "Select Member_Id, Refresh_Token, Email From tbl_Token Where Is_Active = 'Y'"
}


export const DBsp = {
    CreateClientDetails: "call sp_CreateClient(?,?,?,?,?,?,?,?,?,?)",
    CreateMeetingDetails: "call sp_CreateMeeting(?,?,?,?,?,?,?,?,?,?)",
    UpdateDeletedMeetings: "call sp_UpdateDeletedMeeting(?,?,?)",
    GetPatientInfo: "call sp_GetPatientInfo(?,?)",
    GetPatientListBymemberId: "call sp_GetPatientList(?)",
    ReferUser: "call sp_ReferUser(?,?)",
    UpdateMember: "call sp_UpdateMember(?,?,?,?,?,?,?,?,?,?,?,?)",
    GetUpcomingMeetings: "call sp_GetMeetingDetails(?,?)",
    GetMemberInfo: "call sp_GetMemberInfo(?)",
    GetUpcomingAppoinment: "call sp_GetUpcomingMeeting()",
}